---
title: "wk44_tidytuesday"
author: "Sarah Rauf"
date: '2022-11-06'
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

LOading Packages
```{r loading_the_packages}
library(tidyverse)
library(here)
library(janitor)
library(ggrepel)

# importing fonts
library(showtext)
font_add_google("Griffy")
showtext_auto()
windows()
```

Loading the theme()
```{r loading_the_theme}
source(here("functions", "sarah_theme.R"))
theme_set(sarah_theme())
```

Loading the Data
```{r loading_the_data}
data<-read_csv(here("data", "2022", "2022-11-01", "horror_movies.csv"))
```

Reorganizing the Data & Plotting the Graphs
```{r}
table<-data %>% 
  dplyr::mutate(year = lubridate::year(release_date),
                month = lubridate::month(release_date), 
                day = lubridate::day(release_date)) %>% 
  group_by(month) %>%
  summarise(revenue_mean=mean(revenue, na.rm = TRUE)) 

month_written = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
table$month_written<-month_written
table$month_written<-factor(table$month_written, levels=c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))
table

graph <-
  table %>% 
  ggplot() + 
  geom_bar(aes(x=month_written, y=revenue_mean), fill="#FF2C2C", stat='identity') + 
  geom_text(aes(x=month_written, y=revenue_mean, label=round(revenue_mean)), vjust=-0.3, color="white", size=3) + 
  ggtitle("Average Revenue of Horror Movies By Month") +
  theme(plot.title=element_text(size=20, family="Griffy")) + 
  theme(text = element_text(size = 12, family = "Griffy", 
                        face = "plain", 
                        colour = "#FF2C2C", 
                        lineheight = 0.9, 
                        hjust = 0.5, 
                        vjust = 0.5, 
                        angle = 0, 
                        margin = margin(), 
                        debug = FALSE)) +
  theme(panel.background = element_rect(fill = "#000000")) +
  theme(plot.background = element_rect(fill = "#000000")) +
  xlab("Month") + 
  ylab("Average Revenue")
  
```

Saving the Plot
```{r}
ggsave(here("figures", "graph.pdf"), graph,
       width = 190, height = 120, units = "mm")
```

